### PR TITLE
A bunch of stuff, again

### PR DESCRIPTION
**Pull request by AntonC9018**
**Summary**:
- Improve the readme (fix grammar, poor wording; add build instructions, etc.);
- Remove the useless cimgui submodule.
- Provide a utility to build cimgui, dpp, the generator, and run it. Currently only works on Windows. You'll have to fill in Linux and the alike yourself.
- Update bindbc dependencies to `1.0.0`;
- Fix some enum vs version bugs in imgui impls;
- Added honest to goodness spoilers in the readme;
- Some more stuff I missed.

I wouldn't recommend to merge until you fix the generator issues, even though I did a lot of useful stuff. (I spent 3 whole days on this, I don't know why I did this.) Also, the example doesn't build, please figure out why (linker errors, I really have no idea, but probably something to do with the actual commit version of cimgui used). Again, it never worked for me, so I don't have anything to compare against. I'm really looking forward to your help.

Building imgui is no longer a hassle though, use my helper script.

### CODE REVIEW

**Comment by MrcSnm** [comment]
Actually the utility tool, makes the generator don't work correctly.
You can't actually expect that this will work with whatever version it comes, as everyone knows, ImGUI does breaking changes every minor version.

And please refrain from adding useless comments in code.

**Comment by AntonC9018** [comment]
@MrcSnm It takes the specific hash that you had as a submodule. The utility tool does not work not because of the tool, but because the generator fails to write to an absolute path that it gets as an argument, I think. It should theoretically be no different that calling it via command line.

**Comment by AntonC9018** [comment]
I only added comments where it was not clear what the code did, mostly because of the bad variable names. I agree that self-explanatory code does not need comments.

**Comment by MrcSnm** [comment]
I can merge that after it has been tested with the generator changes

**Pull request merged**
